"""added Foreign Key

Revision ID: 2878571ae3a1
Revises: 8c0d9c35196a
Create Date: 2025-01-23 07:19:27.424223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2878571ae3a1'
down_revision = '8c0d9c35196a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_posts_poster_id_users'), 'users', ['poster_id'], ['id'])
        batch_op.drop_column('author')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('username', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.create_unique_constraint('username', ['username'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_posts_poster_id_users'), type_='foreignkey')
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###
